/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Template.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type MutationFunction,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query';

import { customFetch } from './fetcher';

export type AccessTokenResponseTokenType = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type AccessTokenResponseExpiresIn = number | string;

export interface AccessTokenResponse {
  tokenType?: AccessTokenResponseTokenType;
  accessToken: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expiresIn: AccessTokenResponseExpiresIn;
  refreshToken: string;
}

export interface ForgotPasswordRequest {
  email: string;
}

export type HttpValidationProblemDetailsType = null | string;

export type HttpValidationProblemDetailsTitle = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type HttpValidationProblemDetailsStatus = null | number | string;

export type HttpValidationProblemDetailsDetail = null | string;

export type HttpValidationProblemDetailsInstance = null | string;

export type HttpValidationProblemDetailsErrors = { [key: string]: string[] };

export interface HttpValidationProblemDetails {
  type?: HttpValidationProblemDetailsType;
  title?: HttpValidationProblemDetailsTitle;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  status?: HttpValidationProblemDetailsStatus;
  detail?: HttpValidationProblemDetailsDetail;
  instance?: HttpValidationProblemDetailsInstance;
  errors?: HttpValidationProblemDetailsErrors;
}

export type InfoRequestNewEmail = null | string;

export type InfoRequestNewPassword = null | string;

export type InfoRequestOldPassword = null | string;

export interface InfoRequest {
  newEmail?: InfoRequestNewEmail;
  newPassword?: InfoRequestNewPassword;
  oldPassword?: InfoRequestOldPassword;
}

export interface InfoResponse {
  email: string;
  isEmailConfirmed: boolean;
}

export type LoginRequestTwoFactorCode = null | string;

export type LoginRequestTwoFactorRecoveryCode = null | string;

export interface LoginRequest {
  email: string;
  password: string;
  twoFactorCode?: LoginRequestTwoFactorCode;
  twoFactorRecoveryCode?: LoginRequestTwoFactorRecoveryCode;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
}

export interface ResendConfirmationEmailRequest {
  email: string;
}

export interface ResetPasswordRequest {
  email: string;
  resetCode: string;
  newPassword: string;
}

export type TwoFactorRequestEnable = null | boolean;

export type TwoFactorRequestTwoFactorCode = null | string;

export interface TwoFactorRequest {
  enable?: TwoFactorRequestEnable;
  twoFactorCode?: TwoFactorRequestTwoFactorCode;
  resetSharedKey?: boolean;
  resetRecoveryCodes?: boolean;
  forgetMachine?: boolean;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TwoFactorResponseRecoveryCodesLeft = number | string;

export type TwoFactorResponseRecoveryCodes = null | string[];

export interface TwoFactorResponse {
  sharedKey: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  recoveryCodesLeft: TwoFactorResponseRecoveryCodesLeft;
  recoveryCodes?: TwoFactorResponseRecoveryCodes;
  isTwoFactorEnabled: boolean;
  isMachineRemembered: boolean;
}

export type PostApiAuthLoginParams = {
  useCookies?: boolean;
  useSessionCookies?: boolean;
};

export type MapIdentityApiApiAuthConfirmEmailParams = {
  userId: string;
  code: string;
  changedEmail?: string;
};

export type GetApiAuthLoginGoogleParams = {
  returnUrl?: string;
};

export type GetApiAuthGoogleCallbackParams = {
  returnUrl?: string;
};

export const postApiAuthRegister = (
  registerRequest: RegisterRequest,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerRequest,
    signal,
  });
};

export const getPostApiAuthRegisterMutationOptions = <
  TError = HttpValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthRegister'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    { data: RegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRegister>>
>;
export type PostApiAuthRegisterMutationBody = RegisterRequest;
export type PostApiAuthRegisterMutationError = HttpValidationProblemDetails;

export const usePostApiAuthRegister = <
  TError = HttpValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRegister>>,
      TError,
      { data: RegisterRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationOptions = getPostApiAuthRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postApiAuthLogin = (
  loginRequest: LoginRequest,
  params?: PostApiAuthLoginParams,
  signal?: AbortSignal
) => {
  return customFetch<AccessTokenResponse>({
    url: `/api/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginRequest,
    params,
    signal,
  });
};

export const getPostApiAuthLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    TError,
    { data: LoginRequest; params?: PostApiAuthLoginParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: LoginRequest; params?: PostApiAuthLoginParams },
  TContext
> => {
  const mutationKey = ['postApiAuthLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    { data: LoginRequest; params?: PostApiAuthLoginParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return postApiAuthLogin(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogin>>
>;
export type PostApiAuthLoginMutationBody = LoginRequest;
export type PostApiAuthLoginMutationError = unknown;

export const usePostApiAuthLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogin>>,
      TError,
      { data: LoginRequest; params?: PostApiAuthLoginParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: LoginRequest; params?: PostApiAuthLoginParams },
  TContext
> => {
  const mutationOptions = getPostApiAuthLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postApiAuthRefresh = (
  refreshRequest: RefreshRequest,
  signal?: AbortSignal
) => {
  return customFetch<AccessTokenResponse>({
    url: `/api/auth/refresh`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: refreshRequest,
    signal,
  });
};

export const getPostApiAuthRefreshMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRefresh>>,
    TError,
    { data: RefreshRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError,
  { data: RefreshRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthRefresh'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthRefresh>>,
    { data: RefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthRefresh(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRefresh>>
>;
export type PostApiAuthRefreshMutationBody = RefreshRequest;
export type PostApiAuthRefreshMutationError = unknown;

export const usePostApiAuthRefresh = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRefresh>>,
      TError,
      { data: RefreshRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthRefresh>>,
  TError,
  { data: RefreshRequest },
  TContext
> => {
  const mutationOptions = getPostApiAuthRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const mapIdentityApiApiAuthConfirmEmail = (
  params: MapIdentityApiApiAuthConfirmEmailParams,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/confirmEmail`,
    method: 'GET',
    params,
    signal,
  });
};

export const getMapIdentityApiApiAuthConfirmEmailQueryKey = (
  params?: MapIdentityApiApiAuthConfirmEmailParams
) => {
  return [`/api/auth/confirmEmail`, ...(params ? [params] : [])] as const;
};

export const getMapIdentityApiApiAuthConfirmEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
  TError = unknown,
>(
  params: MapIdentityApiApiAuthConfirmEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMapIdentityApiApiAuthConfirmEmailQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>
  > = ({ signal }) => mapIdentityApiApiAuthConfirmEmail(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MapIdentityApiApiAuthConfirmEmailQueryResult = NonNullable<
  Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>
>;
export type MapIdentityApiApiAuthConfirmEmailQueryError = unknown;

export function useMapIdentityApiApiAuthConfirmEmail<
  TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
  TError = unknown,
>(
  params: MapIdentityApiApiAuthConfirmEmailParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
          TError,
          Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMapIdentityApiApiAuthConfirmEmail<
  TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
  TError = unknown,
>(
  params: MapIdentityApiApiAuthConfirmEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
          TError,
          Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMapIdentityApiApiAuthConfirmEmail<
  TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
  TError = unknown,
>(
  params: MapIdentityApiApiAuthConfirmEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMapIdentityApiApiAuthConfirmEmail<
  TData = Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
  TError = unknown,
>(
  params: MapIdentityApiApiAuthConfirmEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof mapIdentityApiApiAuthConfirmEmail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMapIdentityApiApiAuthConfirmEmailQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiAuthResendConfirmationEmail = (
  resendConfirmationEmailRequest: ResendConfirmationEmailRequest,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/resendConfirmationEmail`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: resendConfirmationEmailRequest,
    signal,
  });
};

export const getPostApiAuthResendConfirmationEmailMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
    TError,
    { data: ResendConfirmationEmailRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
  TError,
  { data: ResendConfirmationEmailRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthResendConfirmationEmail'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
    { data: ResendConfirmationEmailRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthResendConfirmationEmail(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthResendConfirmationEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>
>;
export type PostApiAuthResendConfirmationEmailMutationBody =
  ResendConfirmationEmailRequest;
export type PostApiAuthResendConfirmationEmailMutationError = unknown;

export const usePostApiAuthResendConfirmationEmail = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
      TError,
      { data: ResendConfirmationEmailRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthResendConfirmationEmail>>,
  TError,
  { data: ResendConfirmationEmailRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiAuthResendConfirmationEmailMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postApiAuthForgotPassword = (
  forgotPasswordRequest: ForgotPasswordRequest,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/forgot-password`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: forgotPasswordRequest,
    signal,
  });
};

export const getPostApiAuthForgotPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
    TError,
    { data: ForgotPasswordRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
  TError,
  { data: ForgotPasswordRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthForgotPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
    { data: ForgotPasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthForgotPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthForgotPassword>>
>;
export type PostApiAuthForgotPasswordMutationBody = ForgotPasswordRequest;
export type PostApiAuthForgotPasswordMutationError = unknown;

export const usePostApiAuthForgotPassword = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
      TError,
      { data: ForgotPasswordRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthForgotPassword>>,
  TError,
  { data: ForgotPasswordRequest },
  TContext
> => {
  const mutationOptions = getPostApiAuthForgotPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postApiAuthResetPassword = (
  resetPasswordRequest: ResetPasswordRequest,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/resetPassword`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: resetPasswordRequest,
    signal,
  });
};

export const getPostApiAuthResetPasswordMutationOptions = <
  TError = HttpValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthResetPassword>>,
    TError,
    { data: ResetPasswordRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthResetPassword>>,
  TError,
  { data: ResetPasswordRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthResetPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthResetPassword>>,
    { data: ResetPasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthResetPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthResetPassword>>
>;
export type PostApiAuthResetPasswordMutationBody = ResetPasswordRequest;
export type PostApiAuthResetPasswordMutationError =
  HttpValidationProblemDetails;

export const usePostApiAuthResetPassword = <
  TError = HttpValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthResetPassword>>,
      TError,
      { data: ResetPasswordRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthResetPassword>>,
  TError,
  { data: ResetPasswordRequest },
  TContext
> => {
  const mutationOptions = getPostApiAuthResetPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postApiAuthManage2fa = (
  twoFactorRequest: TwoFactorRequest,
  signal?: AbortSignal
) => {
  return customFetch<TwoFactorResponse>({
    url: `/api/auth/manage/2fa`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: twoFactorRequest,
    signal,
  });
};

export const getPostApiAuthManage2faMutationOptions = <
  TError = HttpValidationProblemDetails | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthManage2fa>>,
    TError,
    { data: TwoFactorRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthManage2fa>>,
  TError,
  { data: TwoFactorRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthManage2fa'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthManage2fa>>,
    { data: TwoFactorRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthManage2fa(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthManage2faMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthManage2fa>>
>;
export type PostApiAuthManage2faMutationBody = TwoFactorRequest;
export type PostApiAuthManage2faMutationError =
  HttpValidationProblemDetails | void;

export const usePostApiAuthManage2fa = <
  TError = HttpValidationProblemDetails | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthManage2fa>>,
      TError,
      { data: TwoFactorRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthManage2fa>>,
  TError,
  { data: TwoFactorRequest },
  TContext
> => {
  const mutationOptions = getPostApiAuthManage2faMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const getApiAuthManageInfo = (signal?: AbortSignal) => {
  return customFetch<InfoResponse>({
    url: `/api/auth/manage/info`,
    method: 'GET',
    signal,
  });
};

export const getGetApiAuthManageInfoQueryKey = () => {
  return [`/api/auth/manage/info`] as const;
};

export const getGetApiAuthManageInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>,
  TError = HttpValidationProblemDetails | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiAuthManageInfo>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthManageInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAuthManageInfo>>
  > = ({ signal }) => getApiAuthManageInfo(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthManageInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthManageInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthManageInfo>>
>;
export type GetApiAuthManageInfoQueryError =
  HttpValidationProblemDetails | void;

export function useGetApiAuthManageInfo<
  TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>,
  TError = HttpValidationProblemDetails | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthManageInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthManageInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthManageInfo>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthManageInfo<
  TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>,
  TError = HttpValidationProblemDetails | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthManageInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthManageInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthManageInfo>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthManageInfo<
  TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>,
  TError = HttpValidationProblemDetails | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthManageInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAuthManageInfo<
  TData = Awaited<ReturnType<typeof getApiAuthManageInfo>>,
  TError = HttpValidationProblemDetails | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthManageInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthManageInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiAuthManageInfo = (
  infoRequest: InfoRequest,
  signal?: AbortSignal
) => {
  return customFetch<InfoResponse>({
    url: `/api/auth/manage/info`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: infoRequest,
    signal,
  });
};

export const getPostApiAuthManageInfoMutationOptions = <
  TError = HttpValidationProblemDetails | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthManageInfo>>,
    TError,
    { data: InfoRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthManageInfo>>,
  TError,
  { data: InfoRequest },
  TContext
> => {
  const mutationKey = ['postApiAuthManageInfo'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthManageInfo>>,
    { data: InfoRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthManageInfo(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthManageInfoMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthManageInfo>>
>;
export type PostApiAuthManageInfoMutationBody = InfoRequest;
export type PostApiAuthManageInfoMutationError =
  HttpValidationProblemDetails | void;

export const usePostApiAuthManageInfo = <
  TError = HttpValidationProblemDetails | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthManageInfo>>,
      TError,
      { data: InfoRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthManageInfo>>,
  TError,
  { data: InfoRequest },
  TContext
> => {
  const mutationOptions = getPostApiAuthManageInfoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postApiAuthLogout = (signal?: AbortSignal) => {
  return customFetch<void>({ url: `/api/auth/logout`, method: 'POST', signal });
};

export const getPostApiAuthLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['postApiAuthLogout'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    void
  > = () => {
    return postApiAuthLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogout>>
>;

export type PostApiAuthLogoutMutationError = unknown;

export const usePostApiAuthLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostApiAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const getApiAuthLoginGoogle = (
  params?: GetApiAuthLoginGoogleParams,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/login-google`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetApiAuthLoginGoogleQueryKey = (
  params?: GetApiAuthLoginGoogleParams
) => {
  return [`/api/auth/login-google`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthLoginGoogleQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = unknown,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAuthLoginGoogleQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAuthLoginGoogle>>
  > = ({ signal }) => getApiAuthLoginGoogle(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthLoginGoogleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthLoginGoogle>>
>;
export type GetApiAuthLoginGoogleQueryError = unknown;

export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = unknown,
>(
  params: undefined | GetApiAuthLoginGoogleParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = unknown,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = unknown,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = unknown,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthLoginGoogleQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiAuthGoogleCallback = (
  params?: GetApiAuthGoogleCallbackParams,
  signal?: AbortSignal
) => {
  return customFetch<void>({
    url: `/api/auth/google-callback`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetApiAuthGoogleCallbackQueryKey = (
  params?: GetApiAuthGoogleCallbackParams
) => {
  return [`/api/auth/google-callback`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthGoogleCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
  TError = unknown,
>(
  params?: GetApiAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAuthGoogleCallbackQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
  > = ({ signal }) => getApiAuthGoogleCallback(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthGoogleCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
>;
export type GetApiAuthGoogleCallbackQueryError = unknown;

export function useGetApiAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
  TError = unknown,
>(
  params: undefined | GetApiAuthGoogleCallbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
  TError = unknown,
>(
  params?: GetApiAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
  TError = unknown,
>(
  params?: GetApiAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
  TError = unknown,
>(
  params?: GetApiAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuthGoogleCallbackQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
